title: cd /home/menu
author: pruthvi raj
subtitle: pursuing infosec

url: "https://pruthvirajbhat.github.io"


footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://raw.githubusercontent.com/pruthvirajbhat/pruthvirajbhat.github.io/master/Diya-Gupta.pdf"
